name: Build All

on:
  workflow_dispatch:
    inputs:
      os_version:
        type: string
        required: false
        default: jammy
        description: "version of OS (default = jammy)"
      dotnet_version:
        type: string
        required: false
        default: "8.0"
        description: "version of dotnet (default = 8.0)"

  push:
    branches:
      - master
    paths-ignore:
      - "LICENSE"
      - "**/README.md"
      - "docs/*"

jobs:
  build-sdk-vscode:
    name: Build sdk-vscode
    uses: ulfsoft-harbour/dotnet/.github/workflows/build-and-push.yaml@master
    with:
      target: sdk-vscode
      os_version: ${{ github.event.inputs.os_version }}
      dotnet_version: ${{ github.event.inputs.dotnet_version }}

  build-web-sdk-vscode:
    name: Build web-sdk-vscode
    uses: ulfsoft-harbour/dotnet/.github/workflows/build-and-push.yaml@master
    with:
      target: web-sdk-vscode
      os_version: ${{ github.event.inputs.os_version }}
      dotnet_version: ${{ github.event.inputs.dotnet_version }}
    needs:
      - build-sdk-vscode
